### ISSUE TITLE
Fomula editing

### ISSUE THREAD

**Issue by justinacolmena** [mkulesh/microMathematics#111] opened 2021-11-28 09:14 UTC
I'm a little bit confused. I was able to get a standard bell curve plot out of this program, and obviously it's very capable, but there are a few odd issues with formula editing I just can't figure out, like a simple negation with a minus sign, or I'm forced to use parentheses when a standard order of operations should suffice.
![Screenshot_20211128-000057_microMathematics Plus](https://user-images.githubusercontent.com/32494761/143742550-83135f24-c512-4bc7-b259-b6853f0f587a.jpg)
Mostly FYI I'm just curious. Looks like a case of Einstein disease with vectors and matrices and tensors running all over the place like designing a nuke on your cellphone.

**Comment by mkulesh** [comment] 2022-10-08 20:07
Hi @justinacolmena,
Thank you for the issue. I tested this issue with in version 2.22.1 and the negation with a minus sign works as desired, no parentheses are needed:
![test2](https://user-images.githubusercontent.com/30557348/194726034-eaa3b507-3c27-4fd9-8e31-7c43c785234e.png)

I am currently not able to reproduce this problem.

**Comment by mkulesh** [comment] 2022-10-22 10:29
Closed as non-reproduceable

**Closed by mkulesh** 2022-10-22 10:29 UTC
